namespace KPA_KPI_Analyzer.Diagnostics
{
    partial class ErrorMessageBox
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.txtbx_errorLog = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.pnl_TopPanel = new System.Windows.Forms.Panel();
            this.bunifuCustomLabel1 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btn_Close = new Bunifu.Framework.UI.BunifuImageButton();
            this.btn_ok = new System.Windows.Forms.Button();
            this.dp_errorBoxDragControl = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.pnl_TopPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btn_Close)).BeginInit();
            this.SuspendLayout();
            // 
            // txtbx_errorLog
            // 
            this.txtbx_errorLog.Enabled = false;
            this.txtbx_errorLog.Location = new System.Drawing.Point(12, 89);
            this.txtbx_errorLog.Multiline = true;
            this.txtbx_errorLog.Name = "txtbx_errorLog";
            this.txtbx_errorLog.Size = new System.Drawing.Size(893, 157);
            this.txtbx_errorLog.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.DimGray;
            this.label1.Location = new System.Drawing.Point(12, 62);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(228, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "Errors Generated by KPA-KPI Analyzer:";
            // 
            // pnl_TopPanel
            // 
            this.pnl_TopPanel.BackColor = System.Drawing.Color.Transparent;
            this.pnl_TopPanel.Controls.Add(this.bunifuCustomLabel1);
            this.pnl_TopPanel.Controls.Add(this.btn_Close);
            this.pnl_TopPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnl_TopPanel.Location = new System.Drawing.Point(0, 0);
            this.pnl_TopPanel.Name = "pnl_TopPanel";
            this.pnl_TopPanel.Size = new System.Drawing.Size(917, 50);
            this.pnl_TopPanel.TabIndex = 4;
            // 
            // bunifuCustomLabel1
            // 
            this.bunifuCustomLabel1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuCustomLabel1.AutoSize = true;
            this.bunifuCustomLabel1.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuCustomLabel1.Location = new System.Drawing.Point(12, 18);
            this.bunifuCustomLabel1.Name = "bunifuCustomLabel1";
            this.bunifuCustomLabel1.Size = new System.Drawing.Size(84, 13);
            this.bunifuCustomLabel1.TabIndex = 2;
            this.bunifuCustomLabel1.Text = "Application Error";
            // 
            // btn_Close
            // 
            this.btn_Close.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_Close.BackColor = System.Drawing.Color.Transparent;
            this.btn_Close.ImageActive = null;
            this.btn_Close.Location = new System.Drawing.Point(865, 0);
            this.btn_Close.Name = "btn_Close";
            this.btn_Close.Size = new System.Drawing.Size(52, 50);
            this.btn_Close.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.btn_Close.TabIndex = 3;
            this.btn_Close.TabStop = false;
            this.btn_Close.Zoom = 10;
            this.btn_Close.MouseHover += new System.EventHandler(this.btn_Close_MouseHover);
            // 
            // btn_ok
            // 
            this.btn_ok.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btn_ok.FlatAppearance.BorderColor = System.Drawing.Color.Coral;
            this.btn_ok.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Coral;
            this.btn_ok.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Coral;
            this.btn_ok.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btn_ok.ForeColor = System.Drawing.Color.Coral;
            this.btn_ok.Location = new System.Drawing.Point(721, 252);
            this.btn_ok.Name = "btn_ok";
            this.btn_ok.Size = new System.Drawing.Size(184, 34);
            this.btn_ok.TabIndex = 5;
            this.btn_ok.Text = "OK";
            this.btn_ok.UseVisualStyleBackColor = true;
            this.btn_ok.MouseLeave += new System.EventHandler(this.btn_ok_MouseLeave);
            this.btn_ok.MouseHover += new System.EventHandler(this.btn_ok_MouseHover);
            // 
            // dp_errorBoxDragControl
            // 
            this.dp_errorBoxDragControl.Fixed = true;
            this.dp_errorBoxDragControl.Horizontal = true;
            this.dp_errorBoxDragControl.TargetControl = this.pnl_TopPanel;
            this.dp_errorBoxDragControl.Vertical = true;
            // 
            // ErrorMessageBox
            // 
            this.AcceptButton = this.btn_ok;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(917, 298);
            this.Controls.Add(this.btn_ok);
            this.Controls.Add(this.pnl_TopPanel);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtbx_errorLog);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "ErrorMessageBox";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ErrorMessageBox";
            this.Load += new System.EventHandler(this.ErrorMessageBox_Load);
            this.pnl_TopPanel.ResumeLayout(false);
            this.pnl_TopPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btn_Close)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.TextBox txtbx_errorLog;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel pnl_TopPanel;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel1;
        private Bunifu.Framework.UI.BunifuImageButton btn_Close;
        private System.Windows.Forms.Button btn_ok;
        private Bunifu.Framework.UI.BunifuDragControl dp_errorBoxDragControl;
    }
}